### ISSUE TITLE
Delegate gets released and delegate methods are not called

### ISSUE THREAD

**Issue by phillipie99** [rnystrom/RNGridMenu#11]
I was having problems with the delegate methods not getting called as the delegate was being released. Changing the delegate to a strong reference in the .h fixed it.

Ex.
// An optional delegate to receive information about what items were selected
@property (nonatomic, strong) id<RNGridMenuDelegate> delegate;

**Comment by rnystrom** [comment]
The only issue with this is delegates should really be <code>weak</code> references to avoid retain cycles. I'd be curious in learning on what type of object is delegating and how it is doing so. I'd say that this is a sign that there is some structural issues with how you've got things setup.

Feel free to post some psuedu setup.
