### ISSUE TITLE
Wrong layout in Grid if item count is not divisble by 3

### ISSUE THREAD

**Issue by thaberkern** [rnystrom/RNGridMenu#14]
I have a grid with 8 and 10 menu items. Both render wrong on a iphone.

First of all on iPhone a max. of 3 Items per row is best. RNGridMenu chooses 4.

If I have 10 Menu items. The get layouted at the moment as:

```
x x x x
x     x
  x x 
```

which means 2 are missing

If I have 8 items they get layouted as 2 rows of 4 which can't display on iphone

**Comment by rnystrom** [comment]
Fixed in https://github.com/rnystrom/RNGridMenu/pull/15. Again, really appreciate it.
