### ISSUE TITLE
willDismissWithButtonIndex:option: not being called

### ISSUE THREAD

**Issue by nfitzpatrick** [rnystrom/RNGridMenu#3]
``` c++
- (void)gridMenu:(RNGridMenu *)alertView willDismissWithButtonIndex:(NSInteger)buttonIndex option:(NSString *)option
{
    NSLog(@"selected index %i with option %@",buttonIndex,option);
}
```

is not being called, the selected button is not being reported. Nothing is being logged.

**Comment by slsamliu** [comment]
There is an extra semicolon in 
            if ([self.delegate respondsToSelector:@selector(gridMenu:willDismissWithButtonIndex:option::)

remove that will fix this issue

**Comment by rnystrom** [comment]
Fixed in https://github.com/rnystrom/RNGridMenu/commit/b490c6e623f075cf9f6d541931e0c348b4bd5cd0. Good catch.
