### ISSUE TITLE
Pod

### ISSUE THREAD

**Issue by shmidt** [rnystrom/RNGridMenu#7]
Can you please create a pod for it?
P.S. If you don't know how to do it, I can do it for you.

**Comment by rnystrom** [comment]
On my Todo list once I feel its at a stable and feature-rich point. Still only about 2 weeks old now and I want to add a couple features. It'll be done pretty soon though. Thanks!

**Comment by shmidt** [comment]
@rnystrom Thanks a lot :+1:

**Comment by rnystrom** [comment]
I'm going to keep this open as an enhancement as a reminder to do it :)

**Comment by kurtbradd** [comment]
Is there anyway to setup a notification when the pod is available? Thanks mate!

**Comment by shmidt** [comment]
@kurtbradd  No, I don't think so. But there is a RSS-feed on CocoaPods site that lists all updates: 
feeds.cocoapods.org/new-pods.rss

**Comment by rnystrom** [comment]
I do wish there were a way to get custom notifications. Sounds like a simple SaaS to me ;)

**Comment by thaberkern** [comment]
would love to have a pod

**Comment by RobertAudi** [comment]
+1 for the Pod. I think that even if it's not "stable" it should have a pod to be honest.

**Comment by rnystrom** [comment]
Fixed by @thaberkern in https://github.com/rnystrom/RNGridMenu/commit/9983a047bd6bc2d4d82633927f721953c17e2beb
